export const GET_TASKS = "GET_TASKS";
export const SET_TASKS = "SET_TASKS";
export const DELETE_TASK = "DELETE_TASK";
export const EDIT_TASK = "EDIT_TASK";
export const POST_TASK = "POST_TASK";
export const EDIT_TASK_PROPERTY = "EDIT_TASK_PROPERTY";
export const DELETE_FROM_ALL_TASKS_ARRAY = "DELETE_FROM_ALL_TASKS_ARRAY";
export const UPDATE_TASK_IN_ALL_TASKS_ARRAY = "UPDATE_TASK_IN_ALL_TASKS_ARRAY";
